Feature/login
Medical-Health-Makeit-Project/Backend pull request #3
Opened 2023-04-13 03:33 UTC by JeanVittory

## Summary

Started authorization module using JOI as sanitization tool and controllers along with object oriented service.

### TO-DO

It is necessary to complete the registration and the encryption and decryption to register and login users

2023-04-13 15:35 UTC, ht1204 commented on src/api/service/Auth.service.ts
> +      console.log(user);
What is this console.log doing?

2023-04-13 15:36 UTC, ht1204 commented on src/api/service/Auth.service.ts
> +//   ...userData
What is this commented code doing?

2023-04-13 15:42 UTC, ht1204 commented on src/config/signal/handlerSignal.signal.ts
> +    process.exit(1);
As a tech advice (according to something that I faced before), do not abuse of setTimeout in cases like this in back neither frontend, this could cause any lack of memory or non desirable behaviors, I would recommend a refactor like this:
```js
const HANDLE_SIGNAL_TIME = 10_000;
const timer = setTimeout(() => {
    logger.info('Could not close server in time. Forcibly terminating process.');
    process.exit(1);
  }, HANDLE_SIGNAL_TIME);
clearTimeout(timer);
```
That would cover anything that could happen in cases like this, it's like a patch, but it's more acceptable.

2023-04-13 15:43 UTC, ht1204 commented on src/index.ts
> +  logger.error('UncaughtException Bye!');
Bye! hahaha, LMAO xd

2023-04-13 15:45 UTC, ht1204 commented on src/logs/errors.log
>  2023-04-11T21:03:52.549Z error 403: Authorization denied
I'm not sure if the logs should be here in repo, I think could be better in .gitignore.

2023-04-13 15:48 UTC, ht1204 requested changes
About the rest, great job, but consider the comments for enhancements.

2023-04-14 03:39 UTC, JeanVittory commented on src/config/signal/handlerSignal.signal.ts
> +    process.exit(1);
Great idea Hector! i will analyze your code and put into the project

2023-04-14 03:40 UTC, JeanVittory commented on src/logs/errors.log
>  2023-04-11T21:03:52.549Z error 403: Authorization denied
yeah. they should be at .gitignore...  i will remove them from the repo

2023-04-14 03:59 UTC, JeanVittory commented on src/config/signal/handlerSignal.signal.ts
> +    process.exit(1);
I was thinking about your proposal and got this:
The main idea of ​​the handleSignal function is:

1. receive a signal from the system
2. record it in the log file
3. and finally close the server

if server.close() can't kill all the process like db connections etc inside the app within 10 seconds, then the app will close with a process.exit(1)

in your proposal, you call clearTimeout() immediately, which means that the id timer will be cleared right after of the declaration of the timeOut and the timeout will never be executed so the function's target will be lost.

I remain attentive to your comments

2023-04-14 04:00 UTC, JeanVittory commented on src/index.ts
> +  logger.error('UncaughtException Bye!');
xd

2023-04-14 15:28 UTC, ht1204 commented on src/config/signal/handlerSignal.signal.ts
> +    process.exit(1);
After research and considering your point of view, I do agree with your arguments, I apologize about my tech ignorance, it's the first time that I see this kind of implementation related to processes, specially in TOP as far as I know, it's an excellent approach, keep rocking on it, good one!

2023-04-14 15:38 UTC, JeanVittory commented on src/config/signal/handlerSignal.signal.ts
> +    process.exit(1);
Don't worry Hector! cheers!!! :)

2023-04-14 15:44 UTC, merged

2023-04-14 15:45 UTC, ht1204 reviewed
This was approved after conversation